### ISSUE TITLE
picture title in presentation 

### ISSUE THREAD

**Issue by Soso-h** [gerkovink/markup#41]
Hey Gerko and Hanne, 

A question about my quarto presentation:
Can you help me with figuring out how I can align the caption of the first picture (the koala) on my third presentation slide with the left boundary of said picture (similar to the other two captions of the remaining pictures.)

the link to my quarto presentation code: https://github.com/Soso-h/markup_deliverables/blob/dev/00_exercises/02_presentation/presentation_ex1_v2.qmd

I tried many things with a "div" command including the following, which did not work:

::: columns
::: {.column width="33%"}
![A cute koala](koala.jpg){width="60%"}
<div style="margin-left: 0;">
  **A cute koala**
</div>
:::

just fyi: I replaced the original pictures with arbitrary ones for data protection reasons as I publish this online now

**Comment by hanneoberman** [comment]
Fixed in class today
