### ISSUE TITLE
pictures missing

### ISSUE THREAD

**Issue by laurajochim** [gerkovink/markup#43]
hi! the pictures in 3.6.11 Merging branches and in 3.6.11.1 Resolve the conflict of week 3 are not available:// I think it would make the exercise easier if the visualization would be available. Is it possible to include these? 

Thank you very much!

**Comment by gerkovink** [comment]
This is fixed in #39 and in 81d5f9f. Refreshing the page should suffice. Thanks, for raising the issue!
